# Timeout in seconds before the default entry is booted
timeout: 3

# The boot menu entry
/Sora OS
    # Specify the protocol your kernel uses (Limine protocol)
    protocol: limine

    # Path to your kernel executable (relative to the partition root)
    kernel_path: boot():/boot/sora.elf

